# <font color='blue'><div style="text-align: center">Ch 2. Linked List</font>

* 아래 그림 처럼 노드를 연결시킨 자료구조
* 자료를 연속적인 메모리 공간에 할당할 필요없이 임의 공간에 자료를 저장하고 링크를 이용해 연결함
* 리스트에서 원소를 탐색하기 위해서는 순차탐색을 하여야 함
* 배열에서는 삽입/삭제 시 원소 이동이 필요한데 반해 리스트에서는 삽입/삭제가 원활함
* 리스트 이름 S에는 사과 노드의 주소가 저장됨
* 사과노드는 과일을 저장할 수 있는 장소와 다음 노드의 주소를 저장하는 장소로 구성됨
* 마지막 노드의 링크는 null 이 저장됨
    
![](https://drive.google.com/uc?id=1hgU-79vThtZWe_0wWB0ZTGHmgmPtE020)
        

In [ ]:
class Node:
    def __init__(self, item=None, link=None):
        self.item = item
        self.link = link

apple = Node('사과')
cherry = Node('체리')
pear = Node('배')

print(apple.item)
apple.link = cherry
cherry.link = pear
print(apple.link.item)

print(apple.link.link.item)

사과
체리
배


In [ ]:
class LinkedList:
    def __init__(self):
        self.root = None
        self.n = 0

    def append(self, item):
        newNode = Node(item)
        if self.root == None:
            self.root = newNode
        else:
            curNode = self.root
            while curNode.link != None:
                curNode = curNode.link
            curNode.link = newNode
        self.n += 1

    def insert(self, idx, item):
        newNode = Node(item)
        if idx == 0:
            newNode.link = self.root.link
            self.root = newNode
        elif idx <= self.n - 1:
            curNode = self.root
            for i in range(idx-1):
                curNode = curNode.link
            newNode.link = curNode.link
            curNode.link = newNode
        else:
            print('index Error')
        self.n += 1

    def find(self, item):
        curNode = self.root
        idx = 0
        while curNode.link != None:
            if curNode.item == item:
                return idx
            curNode = curNode.link
            idx += 1
        return -1

    def print(self):
        curNode = self.root
        while curNode.link != None:
            print(curNode.item, end = ' -> ')
            curNode = curNode.link
        print(curNode.item)

In [28]:
a = LinkedList()
a.append('사과')
a.append('앵두')
a.append('배')
a.append('포도')
a.insert(3, '복숭아')

a.print()
a.find('앵두')

사과 -> 앵두 -> 배 -> 복숭아 -> 포도


AttributeError: 'LinkedList' object has no attribute 'find'

In [ ]:
# Node Class: item으로 value를 가지고 link를 가진다. link가 없을 경우, None을 입력한다.
class Node:
    def __init__(self, item=None, link=None): # 객체가 생성될 때 자동으로 실행됨
        self.item = item
        self.link = link

a = Node('사과')
print(a)
print(a.item)
print(a.link)

사과
None


In [ ]:
id(a)

140526501310432

In [ ]:
b = Node('앵두')
id(b)

140526501301648

In [ ]:
fruits = LinkedList()
fruits.append("사과")
fruits.append("앵두")
fruits.append("배")
fruits.append("포도")
fruits.delete("포도")
fruits.get_items()

['사과', '앵두', '배']

In [ ]:
fruits.find("포도")

-1

In [ ]:
fruits.insert(0, "딸기")

In [ ]:
fruits.get_items()

['딸기', '사과', '앵두', '배']

* Linked List 설계
 * root: 리스트 루트 노드이고 Linked List는 root 노드의 주소를 가진다.
   * root = Node()
 * append method: item을 주면 item 노드를 Linked List 마지막 노드에 추가하는 메소드
   * item으로 newNode를 만들고 root의 item이 None이면 newNode를 root로 지정하고 아니면 리스트의 끝까지 이동한 후, 마지막 노드의 링크에 newNode의 주소를 삽입
 * insert method: Linked List에 index로 새 노드를 추가하는 메소드로 index=0 이면 root로 추가하고, index 값에 따라 해당 위치에 삽입한다.
   * index < 0 or index >= listSize 이면 error 메세지를 출력한다.
   * rootNode를 0번째로 보고 index -1 번째 노드의 링크에 newNode를 넣고 newNode의 링크에      index-1 번째 링크에 있던 주소를 넣는다.
 * find Method: Linked List에서 해당 아이템을 찾고 index를 리턴한다.  없으면 -1을 리턴한다.
 * delete method: 주어진 값을 이용해 해당 노드를 찾고 지운다.
   * curNode = preNode = root로 초기 지정하고 curNode를 움직일 때 마다 preNode는 curNode의 이전 노드로 갱신한다
   * del item이 첫번째 노드면 self.root에 del item의 링크를 넣는다.
   * del item이 중간노드면preNode 링크에 del item 링크를 넣는다.
   *  마지막 노드라면 preNode 링크에 None를 넣는다.

 * listSize method: Linked List의 item 수를 리턴한다.

 * get_items method: Linked List item 전체를 리스트로 반환한다.



In [ ]:
class LinkedList:
    def __init__(self):
        self.root = Node()

    def append(self, item):
        if self.root.item == None:
            self.root = Node(item)
        else:
            curNode = self.root
            newNode = Node(item)
            while curNode.link != None:
                curNode = curNode.link
            curNode.link = newNode

    def get_items(self):
        items = []
        curNode = self.root
        while curNode.link != None:
            items.append(curNode.item)
            curNode = curNode.link
        items.append(curNode.item)
        return items

    def size(self):
        curNode = self.root
        if self.root == None:
            return 0
        else:
            cnt = 1
        while curNode.link != None:
            curNode = curNode.link
            cnt += 1
        return cnt

    def search(self, item):
        idx = 0
        curNode = self.root
        while curNode.link != None:
            if curNode.item == item:
                break
            else:
                curNode = curNode.link
                idx += 1
        return idx

    def insert(self, k, item):
        newNode = Node(item)
        curNode = self.root
        if k == 0:
            _tmp = self.root
            self.root = newNode
            newNode.link = _tmp
        elif k > 0:
            for i in range(k-1):
                curNode = curNode.link
            _tmp = curNode.link
            curNode.link = newNode
            newNode.link = _tmp

    def delete(self, item):
        curNode = self.root
        idx = self.search(item)
        if idx == 0:
            self.root = self.root.link
        elif idx > 0:
            for i in range(idx-1):
                curNode = curNode.link
            curNode.link = curNode.link.link

    def pop(self):
        _tmp = self.root.item
        self.root = self.root.link
        return _tmp

In [ ]:
fruits = LinkedList()
fruits.append('사과')
fruits.append('앵두')
fruits.append('배')
print(fruits.get_items())
print(fruits.size())
fruits.insert(2, '딸기')
print(fruits.get_items())
fruits.delete('배')
print(fruits.get_items())
print(fruits.pop())
print(fruits.get_items())

['사과', '앵두', '배']
3
['사과', '앵두', '딸기', '배']
['사과', '앵두', '딸기']
사과
['앵두', '딸기']


#### 리스트 응용문제: 다항식 덧셈

* $ p(x) = 4 x^4 + 3x^2 + 3$ , $ q(x) = 3 x^3 + 4x^2 +2x + 1$ 를 더하면
$ p(x) + q(x) = 4x^4 + 3 x^3 + 7 x^2 + 2x + 4 $ 가 된다.
* 이 연산을 수행하는 프로그램을 만들어 보자.



1.   k차 다항식의 계수를 1차원 배열에 저장하는 방법 예: p = [3,0,3,0,4], q =[1,2,4,3] <br>

2.   k차 다항식의 계수와 차수를 2차원 배열로 저장하는 방법 예: p = [[4,4],[3,2],[3,0]], q = [[3,3],[4,2],[2,1],[1,0]] <br>

3. 2를 Linked List 형식으로 저장하는 방법(숙제로 제출)

####  다항식 덧셈 알고리즘

* Step 0: 덧셈 결과를 기록할 빈 다항식을 만든다.
* Step 1: 두개의 다항식에서 최고 차수를 찾고 최고 차수가 있는 리스트에서 팝하여 결과 다항식에 추가한다. 만약, 최고 차수를 가지는 항이 두개 다항식에 공통으로 존재하면 계수를 합하여 add한다.
* Step 2: 한쪽 다항식이 empty 할 때까지 Step 1을 수행한다.
* Step 3: 비어 있지 않은 다항식의 항을 결과 다항식에 add 한다.

In [ ]:
# method 1
# 두 다항식을 더했을 때, 결과의 차수는 두 다항식 중 최대차수에 의해 결정된다.

class Poly1:
    def __init__(self, maxOrder):
        self.coef = [0] * (maxOrder + 1)
        self.maxOrder = maxOrder

    def setCoef(self, coef, order):
        self.coef[order] = coef

    def get_items(self):
        return self.coef

# 두 다항식 중 작은 차수까지 모든 차수에 대해 계수를 더하고 남은 고차항은 따로 더한다.
    @staticmethod
    def add(p, q):
        if p.maxOrder >= q.maxOrder:
            r = Poly1(p.maxOrder)
            for i in range(q.maxOrder+1):
                r.coef[i] = p.coef[i] + q.coef[i]
            for i in range(q.maxOrder+1, p.maxOrder+1):
                r.coef[i] = p.coef[i]
        else:
            r = Poly1(q.maxOrder)
            for i in range(p.maxOrder+1):
                r.coef[i] = p.coef[i] + q.coef[i]
            for i in range(p.maxOrder+1, q.maxOrder+1):
                r.coef[i] = q.coef[i]
        return r


p = Poly1(4)
p.setCoef(4,4)
p.setCoef(3,2)
p.setCoef(3,0)
print(p.get_items())

q = Poly1(3)
q.setCoef(3,3)
q.setCoef(4,2)
q.setCoef(2,1)
q.setCoef(1,0)
print(q.get_items())

r = Poly1.add(p,q)
print(r.get_items())

[3, 0, 3, 0, 4]
[1, 2, 4, 3]
[4, 2, 7, 3, 4]


In [ ]:
p = Poly1(10)
p.setCoef(3,10)
p.setCoef(2,1)
p.setCoef(7,0)
print(p.get_items())
len(p.coef)

[7, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3]


11

In [ ]:
class Rectangle:
    count = 0  # 클래스 변수

    def __init__(self, width, height):
        self.width = width
        self.height = height
        Rectangle.count += 1

    # 인스턴스 메서드
    def calcArea(self):
        area = self.width * self.height
        return area

    # 정적 메서드
    @staticmethod
    def isSquare(rectWidth, rectHeight):
        return rectWidth == rectHeight

    # 클래스 메서드
    @classmethod
    def printCount(cls):
        print(cls.count)


# 테스트
square = Rectangle.isSquare(5, 5)
print(square)   # True

rect1 = Rectangle(5, 5)
rect1.printCount()  # 1
rect2 = Rectangle(2, 5)
rect2.printCount()  # 2
rect1.printCount()  # 2

True
1
2
2


In [ ]:
x = [1,2,3]
y = x.pop(0)
y, x

(1, [2, 3])

In [ ]:
# method 2
class Poly2:
    def __init__(self):
        self.coef = []

    def setCoef(self,coef):
        self.coef.append(coef)

    def peek(self):
        return self.coef[0][1]

    def pop(self):
        return self.coef.pop(0)

    def size(self):
        return len(self.coef)

    def get_items(self):
        return self.coef

    @staticmethod
    def add(p, q):
        r = Poly2()
        while p.size() > 0 and q.size() > 0:
            if p.peek() > q.peek():
                r.setCoef(p.pop())
            elif p.peek() < q.peek():
                r.setCoef(q.pop())
            else:
                _tmp1 = p.pop()
                _tmp2 = q.pop()
                r.setCoef([_tmp1[0]+_tmp2[0], _tmp1[1]])

        while p.size() > 0:
            r.setCoef(p.pop())
        while q.size() > 0:
            r.setCoef(q.pop())
        return r

p = Poly2()
p.setCoef([4,4])
p.setCoef([3,2])
p.setCoef([3,0])
print(p.get_items())

q = Poly2()
q.setCoef([3,3])
q.setCoef([4,2])
q.setCoef([2,1])
q.setCoef([1,0])
print(q.get_items())

r = Poly2.add(p, q)
print(r.get_items())


[[4, 4], [3, 2], [3, 0]]
[[3, 3], [4, 2], [2, 1], [1, 0]]
[[4, 4], [3, 3], [7, 2], [2, 1], [4, 0]]


In [ ]:
# method 3
class Poly3:
    def __init__(self):
        self.parm = LinkedList()

    def setParm(self, coef, order):
        self.parm.append([coef, order])

    def peek(self):
        return self.parm.root.item[1]

    def pop(self):
        return self.parm.pop()

    def size(self):
        return self.parm.size()

    def get_poly(self):
        return self.parm.get_items()

    @staticmethod
    def add(p, q):
        r = Poly3()
        while (p.size() > 0) and (q.size() > 0):
            if p.peek() > q.peek():
                _tmp = p.pop()
                r.setParm(_tmp[0], _tmp[1])
            elif p.peek() < q.peek():
                _tmp = q.pop()
                r.setParm(_tmp[0], _tmp[1])
            else:
                _tmp1 = p.pop()
                _tmp2 = q.pop()
                r.setParm(_tmp1[0] + _tmp2[0], _tmp1[1])
        if p.size() == 0:
            while q.size() > 0:
                _tmp = q.pop()
                r.setParm(_tmp[0], _tmp[1])
        else:
            while p.size() > 0:
                _tmp = p.pop()
                r.setParm(_tmp[0], _tmp[1])

        return r

p = Poly3()
p.setParm(4,4)
p.setParm(3,2)
p.setParm(3,0)
print(p.get_poly())

q = Poly3()
q.setParm(3,3)
q.setParm(4,2)
q.setParm(2,1)
q.setParm(1,0)
print(q.get_poly())

r = Poly3.add(p, q)
print(r.get_poly())


[[4, 4], [3, 2], [3, 0]]
[[3, 3], [4, 2], [2, 1], [1, 0]]
[[4, 4], [3, 3], [7, 2], [2, 1], [4, 0]]


#### 리스트 응용문제: 희소행렬
* 희소행렬은 행렬 원소에 0이 많이 포함된 행렬을 말한다.
* 희소행렬을 저장할 때, 0도 값이기 때문에 메모리를 차지한다.
* Term-Document Matrix가 대표적인 희소행렬이다.

![그래프](https://drive.google.com/uc?id=1FnZFSrbvGwieHL4wr6G91hEfZX682XbR)

* 희소행렬을 효율적으로 저장하기 위해 아래와 같은 자료구조를 생각할 수 있다.
![그래프](https://drive.google.com/uc?id=1ts4fkwXuu_0MiRP-oMCH17Y9eLl79NQp)
* 0 번째 행에는 행렬의 차원 m, n, non-zero element 수를 추가한다.

* SparseMatrix 자료구조
  * 행렬의 dimension m, n 을 입력받아 희소행렬 리스트를 [[m,n,0]]로 초기 설정한다.
  * append method: [i, j, value] 형태의 리스트를 희소행렬 리스트에 추가한다.
  * shape method: 희소행렬 dimension을 리턴한다.
  * getValue method: i, j 행렬값을 리턴한다.
  * print method: 희소행렬을 일반적 행렬 형태로 프린트한다. (0으로 구성된 m,n array를 만들고 i,j 행렬값을 업데이트한다.)

* 희소행렬의 전치행렬 알고리즘 : 희소행렬의 행 [i,j,val] 을 [j, i, val] 로 바꿔 리턴한다.

* 두 희소행렬의 덧셈 알고리즘:
  * 덧셈 결과를 저장할 빈 희소행렬 c를 만든다.
  * 두 희소행렬 a, b의 unique 한 (i,j) 쌍의 집합을 u 라고 하자.
  * u에서 원소를 하나씩 꺼내면서 a, b의 해당 위치 값을 구해 더한다.
  * 위에서 구한 값이 0이 아니면 c에 추가한다.


In [ ]:
import copy
class SparseMatrix:
    def __init__(self, m, n):
        self.s = [[m,n,0]]
        self.m = m
        self.n = n

    def append(self, i, j, val):
        self.s.append([i,j,val])
        self.s[0][2] += 1

    def peek(self, ii, jj):
        for i in range(1, self.s[0][2]+1):
            if self.s[i][0] == ii and self.s[i][1] == jj:
                return self.s[i][2]
        return 0

    @classmethod
    def transpose(cls, x):
        xt = copy.deepcopy(x)
        for _s in xt.s:
            _s[0], _s[1] = _s[1], _s[0]
        return xt

    def add(cls, a, b):
        for i in range(1, a.s[0][2]+1):
            if peek(a.s[i][0], a.s[i][1]) + peek(b.s[i][0], b.s[i][1]) != 0:



a = SparseMatrix(4,3)
a.append(0,0,1)
a.append(0,2,2)
a.append(1,0,4)
a.append(1,1,6)
a.append(2,2,7)
a.append(3,1,3)

at = SparseMatrix.transpose(a)
at.s

[[3, 4, 6], [0, 0, 1], [2, 0, 2], [0, 1, 4], [1, 1, 6], [2, 2, 7], [1, 3, 3]]

In [ ]:
import numpy as np
import copy

class SparseMatrix:
    def __init__(self, m, n):
        self.m = m
        self.n = n
        self.s = [[m,n,0]]

    def append(self, i, j, val):
        self.s.append([i,j,val])
        self.s[0][2] += 1

    @classmethod
    def transpose(cls, A):
        AT = copy.deepcopy(A)
        for i in range(len(AT.s)):
            AT.s[i][0], AT.s[i][1] = AT.s[i][1], AT.s[i][0]
        return AT

    def pprint(self):
        x = np.zeros((self.m, self.n))
        for i in range(1, len(self.s)):
            x[self.s[i][0]-1, self.s[i][1]-1] = self.s[i][2]
        print(x)

A = SparseMatrix(3,3)
A.append(1,1,1)
A.append(2,2,3)
A.append(2,3,2)
A.append(3,2,4)
A.pprint()
AT = SparseMatrix.transpose(A)
AT.pprint()

[[1. 0. 0.]
 [0. 3. 2.]
 [0. 4. 0.]]
[[1. 0. 0.]
 [0. 3. 4.]
 [0. 2. 0.]]


In [ ]:
import copy
import numpy as np
class SparseMatrix:
    def __init__(self, m, n):
        self.s = [m, n, 0]
        self.m = m
        self.n = n

    def append(self, ii, jj, value):
        updateYN = False
        for i in range(1, len(self.s)):
            if self.s[i][0] == ii and self.s[i][1] == jj:
                self.s[i][2] = value
                updateYN = True
        if updateYN == False:
            self.s.append([i, j, value])
            self.s[0][1] += 1

    def pprint(self):
        res = np.zeros([self.m, self.n])
        for i in range(1, len(self.s)):
            res[self.s[i][0] - 1, self.s[i][1] - 1] = self.s[i][2]
        print(res)

    def getValue(self, ii, jj):
        for i in range(1, len(self.s)):
            if self.s[i][0] == ii and self.s[i][1] == jj:
                return self.s[i][2]
        return 0

    @classmethod
    def transpose(cls, A):
        B = copy.deepcopy(A)
        B.m, B.n = B.n, B.m
        for i in range(len(B.s)):
          B.s[i][0], B.s[i][1] = B.s[i][1], B.s[i][0]
        return B

    @classmethod
    def add(cls, A, B):
        loc_set = set()
        for i in range(1, len(A.s)):
            loc_set.add((A.s[i][0], A.s[i][1]))
        for i in range(1, len(B.s)):
            loc_set.add((B.s[i][0], B.s[i][1]))

        C = SparseMatrix(a.m, a.n)
        for loc in loc_set:
            _tmp1 = A.getValue(loc[0], loc[1])
            _tmp2 = B.getValue(loc[0], loc[1])
            if _tmp1+_tmp2 != 0:
                C.append(loc[0], loc[1], _tmp1+_tmp2)

        return C

    @staticmethod
    def dot(A, B):
        print(A.s[0][0][1], B.s[0][0][0])
        if A.s[0][0][1] != B.s[0][0][0]:
            print("Dimension Error")
        else:
            m = A.s[0][0][0]
            n = B.s[0][0][1]
            l = A.s[0][0][1]

            C = SparseMatrix(m, n)
            for i in range(1, len(A.s)):
                for j in range(1, len(B.s)):
                    if A.s[i][1] == B.s[j][0]:
                        _tmp = C.getValue(A.s[0], B.s[1]) + A.s[i][2] * B.s[j][2]
                        if _tmp != 0:
                            C.append(A.s[0], B.s[1], _tmp)
            return C

a = SparseMatrix(3,3)
a.append(1,1,1.)
a.append(2,3,2.)
a.append(3,2,3.)

b = SparseMatrix(3,3)
b.append(1,1,4.)
b.append(1,2,1.)
b.append(2,1,1.)
b.append(3,1,-1.)
b.append(3,2,1.)
b.append(2,3,-2.)

print(a.s)
print(b.s)
a_T = SparseMatrix.transpose(a)
print(a_T.s)

c = SparseMatrix.add(a,b)
c.pprint()

c_T = SparseMatrix.transpose(c)
c_T.pprint()

a.pprint()
b.pprint()

c = SparseMatrix.dot(a, b)
c.pprint()
print(c.s)

TypeError: 'int' object is not subscriptable

<font color='red'>H.W # 3: 두 희소 행렬의 곱셈을 수행하는 함수를 작성하시오. </font>

$$ C_{ij} = \sum_k A_{ik} \cdot B_{kj} $$

1. 두 행렬의 곱셈은 A는 r by c, B는 c by l 과 같이 A의 열의 수와 B의 행수가 같아야 한다. <br>   아니면 null을 리턴한다. 곱셈 결과 C 행렬은 r by l이 된다.
2. 희소행렬 곱셈 결과를 저장할 빈 리스트를 생성한다.
3.  위의 식 $ C_{ij} $ 를 계산해서 그 값이 0 이 아니면 C 희소행렬에 (i,j, 계산값)을 추가한다.
4. C 희소행렬에  add 한 개수와 결과 dimension을 계산한 후, 헤더를 업데이트 한다.
5. C 희소행렬을 반환한다.


In [ ]:
def dot(a, b):
    if a.shape()[1] != b.shape()[0]:
        print("Dimension Error")
    else:
        m = a.shape()[0]
        n = b.shape()[1]
        l = a.shape()[1]

        c = SparseMatrix(m, n)
        for i in range(1, m+1):
            for j in range(1, n+1):
                _sum = 0
                for k in range(1, l+1):
                    _sum += a.getValue(i,k) * b.getValue(k,j)
                if _sum != 0:
                    c.append(i, j, _sum)
        return c

c = mult(a,b)
c.print()


[[4. 7. 0.]
 [0. 0. 4.]
 [0. 0. 3.]]


### Double Linked List

* Double Linked List는 아래 그림처럼 링크가 좌, 우에 두개가 존재하는 Linked List다.
* Single Linked List는 삭제를 위해서 preNode를 관리해야 하는 불편함이 있는데 Double Linked List는 preNode를 알 수 있는 장점은 있지만 이를 위해 링크를 두 개 관리해야 하는 손실이 있다.

<center><img src="https://drive.google.com/uc?id=1j6jPGZXhkZJ1F-374xM9Avvoq0CwYcCt" width="300" height="500" /></center>

![](https://drive.google.com/uc?id=1STHXAzEkDwb0ailRcZuRNKU_TGYI3RJK)
        
* Double Linked List 설계

 * DNode: item과 left, right에 각각 좌, 우 노드의 주소를 저장한다.

 * root: 리스트 루트 노드이고 Double Linked List는 root 노드의 주소를 가진다.
    * root = DNode()
    
  * append method: item을 주면 item을 가진 새 노드를 Linked List 마지막 노드에 추가하는 메소드
   * newNode를 만들고 root의 item이 None이면 newNode를 root로 지정하고 아니면 리스트의 끝까지 이동한 후, 마지막 노드의 right에 newNode의 주소를 삽입하고 newNode의 left에 마지막 노드의 주소를 삽입한다.

 * insert method: Linked List에 index로 새 노드를 추가하는 메소드로 index=0 이면 root로 추가하고, index 값에 따라 해당 위치에 삽입한다.
   * index < 0 or index >= listSize 이면 error 메세지를 출력한다.
   * rootNode를 0번째로 보고 index -1 번째 노드 주소를 newNode의 left에 넣고, index번째 노드의 주소를 newNode right에 넣는다.
   
 * find Method: Linked List에서 해당 아이템을 찾고 index를 리턴한다.  없으면 -1을 리턴한다.

 * delete method: 주어진 값을 이용해 해당 노드를 찾고 지운다.
   * del item이 첫번째 노드면 self.root에 self.root.right를 넣고 self.root.left에 None를 넣는다.
   * del item이 중간노드면 delNode.left.right에 delNode.right를 삽입한다.
   * 마지막 노드라면 마지막 노드 left.right에 None를 삽입한다.

 * listSize method: Linked List의 item 수를 리턴한다.

 * print method: Linked List를 print 한다.

In [ ]:
# Node Class: item으로 value를 가지고 right, left를 가진다. link가 없을 경우, None을 입력한다.
class DNode:
    def __init__(self, item=None):
        self.item = item
        self.right = None
        self.left = None

a = DNode('사과')
print(id(a))

140323005905360


In [ ]:
class DoubleLinkedList:
    def __init__(self):
        self.root = DNode()

    def append(self, item):
        newNode = DNode(item)
        if self.root.item == None:
            self.root = newNode
        else:
            curNode = self.root
            while curNode.right != None:
                curNode = curNode.right
            curNode.right = newNode
            newNode.left = curNode

    def delete(self, item):
        curNode = self.root
        if curNode.item == item:
             self.root = self.root.right
             self.root.left = None
        else:
            while curNode.right != None:
                curNode = curNode.right
                if curNode.item == item:
                    if curNode.right == None:   # 끝노드
                        curNode.left.right = None
                    else:                       # 중간노드
                        curNode.left.right = curNode.right
                        curNode.right.left = curNode.left

    def print(self):
        curNode = self.root
        while curNode.right != None:
            print(curNode.item, end = ", ")
            curNode = curNode.right
        print(curNode.item)



In [ ]:
fruits = DoubleLinkedList()
fruits.append("사과")
fruits.append("오렌지")
fruits.append("배")
fruits.append("포도")

fruits.delete("배")
fruits.print()

사과, 오렌지, 포도


H.W # 3: Double Linked List 클래스를 작성하시오.

### Circle Linked List

* Circle Linked List는 아래 그림처럼 마지막 노드의 링크에 root 노드의 주소를 삽입한 것이다.
* Single Linked List는 항상 root로 부터 순차탐색을 해야 하는데 Circle Linked List는 아무 위치에서나 원형으로 탐색이 가능하다.
* 무한반복 mp3, 혹은 사진 슬라이드 쇼 플레이 순서를 만드는 예와 같이 순서가 계속 반복되는 원형 자료구조에 적합하다.

![](https://drive.google.com/uc?id=17AbC2e28EEN8f7RTQUl4uUbgn5ueAeUb)

* Circle Linked List 설계
 * root: 리스트 루트 노드이고 Linked List는 root 노드의 주소를 가진다.   root = Node()
 * tail : 리스트 마지막 노드이고 tail.link = root 가 된다. 마지막 노드를 관리하는 이유는 루트가 삭제될 경우, tail.link를 갱신해야 하기 때문이다.
 * current: 리스트 순환을 위해 현재 노드를 관리한다.
  
 * append method: item을 주면 item 노드를 tail 노드 다음에 추가하는 메소드
   * newNode를 만들고 root의 item이 None이면 newNode를 root와 tail로 지정하고 newNode 링크에 root 주소를 삽입한다.  아니면 tail 링크에 newNode의 주소를 삽입하고 newNode 링크에는 root 주소를 삽입한다. 이후, newNode를 tail로 갱신한다.

 * setCurrent method: 리스트에서 item을 가지는 노드를 current 노드로 지정한다.
 * moveNext method: current 노드를 다음 노드로 바꾼다.
  * insert method: current 노드 다음에 새노드를 삽입한다.
   * current 노드 링크에 새 노드를 지정하고 새노드의 링크에 current 노드에 연결되어 있던 링크를 지정하여 연결한다.
   * 만약, current가 tail 노드 였다면 새노드를 tail 노드로 재지정한다.

 * delete method: 주어진 값을 이용해 해당 노드를 찾고 지운다.
   * curNode = preNode = root로 초기 지정하고 curNode를 움직일 때 마다 preNode는 curNode의 이전 노드로 갱신한다.
   * del item이 첫번째 노드면 root에 del item의 링크를 넣고 tail노드의 링크에 값을 root로 갱신한다.
   * del item이 중간노드면 preNode 링크에 del item의 링크를 넣는다.
   *  마지막 노드라면 preNode 링크에 del item의 링크를 넣고 tail 노드를 preNode로 갱신한다.

In [ ]:
class Node:
    def __init__(self, item=None):
        self.item = item
        self.link = None

a = Node("딸기")
b = Node("바나나")
a, b


(<__main__.Node at 0x7fb75855aa90>, <__main__.Node at 0x7fb75855acd0>)

In [ ]:
class Node:
    def __init__(self, item=None, link = None):
        self.item = item
        self.link = link

class CircleLinkedList:
    def __init__(self):
        self.root = Node()    # 시작노드
        self.tail = self.root # 끝노드
        self.current = self.root

    def append(self, item):
        # 추가할 새노드를 만든다.
        newNode = Node(item)
        # 루트가 비어 있으면 루트와 테일을 새노드로 지정한다.
        if self.root.item == None:
            self.root = newNode
            self.tail = newNode
            newNode.link = self.root
        else:
        # 루트가 비어 있지 않으면 테일 뒤에 새노드를 추가하고 테일을 업데이트한다.
            self.tail.link = newNode
            newNode.link = self.root
            self.tail = newNode

    # 리스트 안에 모든 노드를 프린트 한다.
    def pprint(self):
        curNode = self.root
        print(curNode.item)
        while curNode.link != self.root:
            curNode = curNode.link
            print(curNode.item)

    # 리스트에 존재하는 노드 수를 구한다.
    def listSize(self):
        curNode = self.root
        cnt = 1
        while curNode.link != self.root:
            curNode = curNode.link
            cnt += 1
        return cnt

    # 리스트에서 item을 가지는 노드를 current 노드로 지정한다.
    def setCurrent(self,item):
        curNode = self.root
        for i in range(self.listSize()):
            if curNode.item != item:
                curNode = curNode.link
            else:
                self.current = curNode
                break

    # current 노드를 다음 노드로 바꾼다.
    def moveNext(self):
        self.current = self.current.link
        print("현재 위치는 ", self.current.item, "입니다.")

    # current 다음에 item을 삽입한다.
    def insert(self, item):
        # 삽입할 새 노드를 만든다.
        newNode = Node(item)
        # current 노드의 링크에 새 노드를 지정하고 새노드의 링크에 current 노드가 연결되어 있던 링크를 지정하여 연결한다.
        _tmp = self.current.link
        self.current.link = newNode
        newNode.link = _tmp
        # 만약, item1이 tail 노드 였다면 새노드를 tail 노드로 재지정한다.
        if self.current == self.tail:
            self.tail = newNode

    # item을 가지는 노드를 삭제한다.
    def delete(self, item):
        delYN = False
        # 루트가 삭제 대상 노드인지 확인한다. 루트를 삭제할 경우, 루트 다음 노드를 루트로 갱신하고 tail 노드의 링크를 갱신된 루트로 재지정한다.
        curNode = self.root
        if curNode.item == item:
            self.root = self.root.link
            self.tail.link = self.root
            delYN = True
        # 루트가 삭제 대상이 아닐 경우, 끝까지 탐색하면서 item이 존재하는 노드를 찾는다.
        # 찾았다면 preNode의 링크에 대상노드 링크를 넘겨준다. 만약, 대상 노드가 tail노드라면 tail 노드를 preNode로 변경한다.
        else:
            while curNode.link != self.root:
                preNode = curNode
                curNode = curNode.link
                if curNode.item == item:
                    preNode.link = curNode.link
                    if curNode == self.tail:
                        self.tail = preNode
                    delYN = True
        # 삭제를 하지 못했으면 error message를 출력한다.
        if delYN == False: print("delete failed")

fruits = CircleLinkedList()
fruits.append('사과')
fruits.append('앵두')
fruits.append('오렌지')
fruits.append('포도')

fruits.pprint()
print(fruits.listSize())
fruits.setCurrent("포도")
fruits.insert("수박")
print(fruits.tail.item)
fruits.pprint()

사과
앵두
오렌지
포도
4
수박
사과
앵두
오렌지
포도
수박


In [ ]:
fruits.setCurrent('오렌지')
for i in range(10):
    fruits.moveNext()

현재 위치는  포도 입니다.
현재 위치는  수박 입니다.
현재 위치는  사과 입니다.
현재 위치는  앵두 입니다.
현재 위치는  오렌지 입니다.
현재 위치는  포도 입니다.
현재 위치는  수박 입니다.
현재 위치는  사과 입니다.
현재 위치는  앵두 입니다.
현재 위치는  오렌지 입니다.


아래는 이미지 파일을 선택해 보여주는 PyQT 프로그램이다. 이 프로그램을 수정하여 이미지 폴더를 선택하면 그 안의 모든 파일을 순환적으로 보여주는 기능과 무작위로 섞어 보여주는 프로그램으로 바꾸세요.

In [ ]:
# PyQT Version
import sys
from PyQt5.QtWidgets import QMainWindow,QApplication, qApp, QFileDialog
from PyQt5.uic import loadUiType
from PyQt5.QtGui import *

form_class = loadUiType("imageViewer.ui")[0]

class ViewerClass(QMainWindow, form_class):
    def __init__(self, parent=None):
        QMainWindow.__init__(self,parent)
        self.setupUi(self)
        self.actionSelect.triggered.connect(self.fileSelect)
        self.actionExit.triggered.connect(qApp.quit)

    def fileSelect(self):
        fname = QFileDialog.getOpenFileName(self)
        qPixmapVar = QPixmap()
        qPixmapVar.load(fname[0])
        qPixmapVar = qPixmapVar.scaled(700, 400, aspectRatioMode=True)
        self.label.setPixmap(qPixmapVar)

app = QApplication(sys.argv)
myWindow = ViewerClass(None)
myWindow.show()
app.exec_()

ModuleNotFoundError: ignored

In [ ]:
# lllist 패키지 사용
!pip install llist

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.0/43.0 kB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for llist: filename=llist-0.7.1-cp310-cp310-linux_x86_64.whl size=74083 sha256=701d49e1755f15edf24f9296be68d64ba46f453f5c40d4c205791bc800bd41ba
  Stored in directory: /root/.cache/pip/wheels/e9/91/41/252becb26acf296e14913e0ee13940295bc475be57aed9bb2e
Successfully built llist


In [ ]:
# importing packages
import llist
from llist import sllist,sllistnode

# creating a singly linked list
lst = sllist(['first','second','third'])
print(lst)
print(lst.first.value)
print(lst.last.value)
print(lst.size)
print()

# adding and inserting values
lst.append('fourth')
node = lst.nodeat(2) # 2번쨰 노드 지정
lst.insertafter('fifth',node) # 두번째 노드 다음에 삽입

print(lst)
print(lst.first)
print(lst.last)
print(lst.size)
print()

# popping a value
#i.e. removing the last entry
# of the list
lst.pop()
print(lst)
print(lst.first)
print(lst.last)
print(lst.size)
print()

# removing a specific element
node = lst.nodeat(1)
lst.remove(node)
print(lst)
print(lst.first)
print(lst.last)
print(lst.size)
print()


sllist([first, second, third])
first
third
3

sllist([first, second, third, fifth, fourth])
sllistnode(first)
sllistnode(fourth)
5

sllist([first, second, third, fifth])
sllistnode(first)
sllistnode(fifth)
4

sllist([first, third, fifth])
sllistnode(first)
sllistnode(fifth)
3

