In [3]:
import numpy as np

class Node:
    def __init__(self, feature=None, threshold=None, left=None, right=None, value=None):
        self.feature = feature
        self.threshold = threshold
        self.left = left
        self.right = right
        self.value = value

class DecisionTree:
    def __init__(self, data, labels, depth=0, max_depth=5):
        self.data = data
        self.labels = labels
        self.dtype = dtype
        self.depth = depth
        self.max_depth = max_depth

    def build_tree(self):
        self._build_tree(self.data, self.labels, self.depth, self.max_depth)

    def _build_tree(self, data, labels, depth, max_depth):
        print(data, labels)
        print('------')
        # Stopping criteria
        if len(set(labels)) == 1 or depth == max_depth:
            return Node(value=labels[0])

        # Select the best feature and threshold
        best_feature, best_threshold = self.select_best_split(data, labels)

        # Split the data
        left_indices = data[:, best_feature] < best_threshold
        right_indices = data[:, best_feature] >= best_threshold

        # Create child nodes
        left_child = self._build_tree(data[left_indices], labels[left_indices], depth + 1, max_depth)
        right_child = self._build_tree(data[right_indices], labels[right_indices], depth + 1, max_depth)

        return Node(feature=best_feature, threshold=best_threshold, left=left_child, right=right_child)

    def impurity(self, labels, method='entropy'):
        """Calculate the Gini impurity for a list of labels."""
        _, counts = np.unique(labels, return_counts=True)
        probabilities = counts / len(labels)
        if method == 'entropy':
            return np.sum(-probabilities * np.log2(probabilities))
        else:
            return 1 - np.sum(probabilities ** 2)

    def information_gain(self, left_labels, right_labels, current_impurity):
        """Calculate the information gain of a split."""
        p = len(left_labels) / (len(left_labels) + len(right_labels))
        return current_impurity - p * self.impurity(left_labels) - (1 - p) * self.impurity(right_labels)

    def select_best_split(self, data, labels):
        """Select the best feature and threshold to split the data."""
        best_gain = 0
        best_feature = None
        best_threshold = None
        current_impurity = self.impurity(labels)

        n_features = data.shape[1]

        for feature in range(n_features):
            thresholds = np.unique(data[:, feature])
            for threshold in thresholds:
                left_indices = data[:, feature] < threshold
                right_indices = data[:, feature] >= threshold
                left_labels = labels[left_indices]
                right_labels = labels[right_indices]

                if len(left_labels) == 0 or len(right_labels) == 0:
                    continue

                gain = self.information_gain(left_labels, right_labels, current_impurity)

                if gain > best_gain:
                    best_gain = gain
                    best_feature = feature
                    best_threshold = threshold

        return best_feature, best_threshold

In [5]:
# Example usage
data = np.array([[2.3, 4.5], [1.3, 3.5], [3.3, 2.5]])
labels = np.array([0, 1, 0])
tree = DecisionTree(data, labels)
tree.build_tree()

[[2.3 4.5]
 [1.3 3.5]
 [3.3 2.5]] [0 1 0]
------
[[1.3 3.5]] [1]
------
[[2.3 4.5]
 [3.3 2.5]] [0 0]
------
