In [0]:
x = [1,2,3]

x.append(4)
x

[1, 2, 3, 4]

In [0]:
x.insert(2,5)
x

[1, 2, 5, 3, 4]

In [0]:
x.pop(0)

1

In [0]:
class Imsi:
    def __init__(self):
        self.cnt = 1
        self.x = [1,2,3]
    def size(self):
        return len(self.x)

a = Imsi()
a.size()

3

In [0]:
# 다항식 p(x) 를 저장하는 자료구조: [[4,4], [3,2], [3,0]]
# add method: 리스트 자료구조에 [coef, k] 형식의 서브 리스트를 추가한다.
# peek method: 0번째 리스트 원소를 리턴한다.
# pop method: 0번째 리스트 원소를 꺼내 리턴한다.
# size method: 리스트의 길이를 리턴한다.
# print method: 다항식 형태를 프린트 한다.
class Poly:
    def __init__(self):
        self.eq = []
    def add(self, term):
        self.eq.append(term)
    def peek(self):
        return self.eq[0]
    def pop(self):
        return self.eq.pop(0)
    def size(self):
        return len(self.eq)
    def print(self):
        for term in self.eq:
            print("%dx^%d + " %(term[0], term[1]), end = "")

p = Poly()
p.add([4,4])
p.add([3,2])
p.add([3,0])
p.print()
print()
q = Poly()
q.add([3,3])
q.add([4,2])
q.add([2,1])
q.add([1,0])
q.print()

4x^4 + 3x^2 + 3x^0 + 
3x^3 + 4x^2 + 2x^1 + 1x^0 + 

In [0]:
class PolyCalc:
    @classmethod
    def add(cls, p, q):
        r = Poly()
        while (p.size() > 0) and (q.size() > 0):
            if p.peek()[1] > q.peek()[1]:
                r.add(p.pop())
            elif p.peek()[1] < q.peek()[1]:
                r.add(q.pop())
            else:
                _tmp1 = p.pop()
                _tmp2 = q.pop()
                r.add([_tmp1[0]+_tmp2[0], _tmp1[1]])
        while p.size() > 0:
            r.add(p.pop())
        while q.size() > 0:
            r.add(q.pop())
        return r

c = PolyCalc()
c.add

c = PolyCalc.add(p,q)
c.print()

4x^4 + 3x^3 + 7x^2 + 2x^1 + 4x^0 + 

In [0]:
class SparseMatrix:
    def __init__(self, m, n):
        self.m = m
        self.n = n
        self.sm = [[m,n,0]]
    def append(self,i,j,val):
        if val != 0:
            self.sm.append([i,j,val])
        self.sm[0][2] = len(self.sm) - 1
    def print(self):
        import numpy as np
        _tmp = np.zeros((self.m,self.n))
        for i in range(1, len(self.sm)):
            _tmp[self.sm[i][0]-1, self.sm[i][1]-1] = self.sm[i][2]
        print(_tmp)

p = SparseMatrix(3,3)
p.append(1,1,1)
p.append(2,2,2)
p.append(3,3,3)
p.print()

q = SparseMatrix(3,3)
q.append(1,1,4)
q.append(2,1,2)
q.append(2,2,3)
q.append(3,2,7)
q.append(3,1,5)
q.print()
q.sm

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[[4. 0. 0.]
 [2. 3. 0.]
 [5. 7. 0.]]


[[3, 3, 5], [1, 1, 4], [2, 1, 2], [2, 2, 3], [3, 2, 7], [3, 1, 5]]

In [0]:
import copy
class SparseMatrixCalc:
    @classmethod
    def transpose(cls, A):
        for term in A.sm:
            term[0], term[1] = term[1], term[0]
        return A
print(q.sm)
q1 = copy.deepcopy(q)
B = SparseMatrixCalc.transpose(q1)
# B.print()
print(B.sm)

[[3, 3, 5], [1, 1, 4], [2, 1, 2], [2, 2, 3], [3, 2, 7], [3, 1, 5]]
[[3, 3, 5], [1, 1, 4], [1, 2, 2], [2, 2, 3], [2, 3, 7], [1, 3, 5]]
