In [ ]:
a = 54

class DecBin:
    @staticmethod
    def dec2bin(a):
        bin = []
        while a >= 1:
            frac = a % 2
            a = a // 2
            bin.append(str(frac))

        bin = bin[::-1]
        return ''.join(bin)

    @staticmethod
    def bin2dec(x):
        n = len(x)
        dec = 0
        for i in range(n):
            dec += int(x[i])*2**(n-i-1)
        return dec

In [ ]:
DecBin.dec2bin(52), DecBin.bin2dec('110100')

('110100', 52)

In [ ]:
''.join(bin)

'110110'

In [ ]:
class Node:
    def __init__(self, item=None, link=None):
        self.item = item
        self.link = link

In [ ]:
Node("사과")

In [ ]:
class LinkedList:
    def __init__(self):
        self.root = None
        self.nNode = 0

    def append(self,item):
        curNode = self.root
        newNode = Node(item)
        if self.root is None:
            self.root = newNode
        else:
            while curNode.link is not None:
                curNode = curNode.link
            curNode.link = newNode
        self.nNode += 1

    def insert(self, k, item):
        curNode = self.root
        newNode = Node(item)
        if k == 0:
            newNode.link = self.root
            self.root = newNode
        elif k > 0 and k <= self.nNode:
            for i in range(k-1):
                curNode = curNode.link
            _tmp = curNode.link
            curNode.link = newNode
            newNode.link = _tmp
            self.nNode += 1
        else:
            print("Index Error")

    def delete(self, item):
        k = self.find(item)
        curNode = self.root
        if k == 0:
            self.root = self.root.link
        else:
            for i in range(k-1):
                curNode = curNode.link
            curNode.link  =  curNode.link.link

    def find(self, item):
        curNode = self.root
        k = 0
        while curNode.link is not None:
            if item == curNode.item:
                return k
            else:
                curNode = curNode.link
                k += 1
        if item == curNode.item:
            return k
        else:
            return None

    def print(self):
        curNode = self.root
        while curNode.link is not None:
            print(curNode.item, end=' -> ')
            curNode = curNode.link
        print(curNode.item)

In [ ]:
fruits = LinkedList()
fruits.append("사과")
fruits.append("배")
fruits.append("딸기")
fruits.append("포도")
fruits.insert(4,"앵두")
fruits.print()

사과 -> 배 -> 딸기 -> 포도 -> 앵두


In [ ]:
fruits.delete("배")
fruits.print()

사과 -> 딸기 -> 포도 -> 앵두


In [ ]:
import numpy as np

class Desc_Stat:
    def __init__(self, x):
        self.x = x

    def get_mean(self):
        return np.mean(self.x)

    @staticmethod
    def get_cor(x, y):
        n = len(x)

        x_mean = np.mean(x)
        y_mean = np.mean(y)

        sumxy = sumxx = sumyy = 0
        for i in range(n):
            sumxy += (x[i] - x_mean)*(y[i] - y_mean)
            sumxx += (x[i] - x_mean)*(x[i] - x_mean)
            sumyy += (y[i] - y_mean)*(y[i] - y_mean)

        r = sumxy / (np.sqrt(sumxx) * np.sqrt(sumyy))
        return r

x = np.array([1,2,3,4,5])
y = np.array([5,4,3,2,1])

x_obj = Desc_Stat(x)
y_obj = Desc_Stat(y)

x_obj.get_mean(), y_obj.get_mean()

(3.0, 3.0)

In [ ]:
Desc_Stat.get_cor(x, y)

-0.9999999999999998

In [ ]:
x = [1,2,3]
x.pop(-1)

3

In [ ]:
x

[1, 2]

In [ ]:
class Poly1:
    def __init__(self, order):
        self.order = order
        self.coef = [0] * (order+1)

    def set_coef(self, coef, order):
        self.coef[order] = coef

    def peek(self):
        return len(self.coef) - 1

    def pop(self):
        return self.coef.pop(-1), len(self.coef)

    @staticmethod
    def add(p, q):
        r = Poly1(max(p.order, q.order))
        for i in range(max(len(p.coef), len(q.coef))):
            if i >= len(p.coef):
                r.coef[i] = q.coef[i]
            elif i >= len(q.coef):
                r.coef[i] = p.coef[i]
            else:
                r.coef[i] = p.coef[i] + q.coef[i]
        return r


In [ ]:
p = Poly1(4)
p.set_coef(4,4)
p.set_coef(3,2)
p.set_coef(3,0)

q = Poly1(3)
q.set_coef(3,3)
q.set_coef(4,2)
q.set_coef(2,1)
q.set_coef(1,0)

Poly1.add(p, q)

[4, 2, 7, 3, 4]


In [ ]:
import copy
class Poly2:
    def __init__(self):
        self.coef = []

    def set_coef(self, coef, order):
        self.coef.append([coef, order])

    def get_max_order(self):
        if len(self.coef) == 0:
            return -1
        return self.coef[0][1]

    def pop(self):
        if len(self.coef) == 0:
            return None
        return self.coef.pop(0)

    @staticmethod
    def add(_p, _q):
        p = copy.deepcopy(_p)
        q = copy.deepcopy(_q)
        r = Poly2()
        while p.get_max_order() > -1 and q.get_max_order() > -1:
            if p.get_max_order() > q.get_max_order():
                _tmp = p.pop()
                r.set_coef(_tmp[0], _tmp[1])
            elif p.get_max_order() < q.get_max_order():
                _tmp = q.pop()
                r.set_coef(_tmp[0], _tmp[1])
            else:
                _tmp1 = p.pop()
                _tmp2 = q.pop()
                _tmp3 = _tmp1[0]+_tmp2[0]
                if _tmp3 != 0:
                    r.set_coef(_tmp3, _tmp2[1])
        while p.get_max_order() > -1:
            _tmp = p.pop()
            r.set_coef(_tmp[0], _tmp[1])
        while q.get_max_order() > -1:
            _tmp = q.pop()
            r.set_coef(_tmp[0], _tmp[1])
        return r

p = Poly2()
p.set_coef(4,4)
p.set_coef(3,2)
p.set_coef(3,0)

q = Poly2()
q.set_coef(3,3)
q.set_coef(4,2)
q.set_coef(2,1)
q.set_coef(1,0)

r = Poly2.add(p,q)
p.coef, q.coef, r.coef

([[4, 4], [3, 2], [3, 0]],
 [[3, 3], [4, 2], [2, 1], [1, 0]],
 [[4, 4], [3, 3], [7, 2], [2, 1], [4, 0]])

In [ ]:
import numpy as np

class SparseMatrix:
    def __init__(self, m, n):
        self.s = [[m, n, 0]]

    def append(self, i, j, value):
        self.s.append([i,j,value])
        self.s[0][2] += 1

    def shape(self):
        return self.s[0][0], self.s[0][1]

    def get_value(self, ii, jj):
        for i in range(1, len(self.s)):
            if self.s[i][0] == ii and self.s[i][1] == jj:
                return self.s[i][2]
        return 0

    def print_matrix(self):
        X = np.zeros(self.shape())
        for i in range(1, len(self.s)):
            X[self.s[i][0], self.s[i][1]] = self.s[i][2]
        print(X)

    @staticmethod
    def transpose(x):
        x_t = SparseMatrix(x.s[0][1], x.s[0][0])
        x_t.s = x.s[:]

        for i in range(len(x.s)):
            x_t.s[i][0], x_t.s[i][1] = x_t.s[i][1], x_t.s[i][0]
        return x_t

    @staticmethod
    def add(x, y):
        z = SparseMatrix(x.shape()[0], x.shape()[1])
        u = set()
        for i in range(1,len(x.s)):
            u.add((x.s[i][0], x.s[i][1]))
        for i in range(1,len(y.s)):
            u.add((y.s[i][0], y.s[i][1]))
        for _u in u:
            _tmp1 = x.get_value(_u[0], _u[1])
            _tmp2 = y.get_value(_u[0], _u[1])
            if _tmp1 + _tmp2 != 0:
                z.append(_u[0], _u[1],_tmp1 + _tmp2)
        return z


In [ ]:
x = SparseMatrix(8,7)
x.append(0,2,2)
x.append(0,6,12)
x.append(1,4,7)
x.append(2,0,23)
x.append(3,3,31)
x.append(4,1,14)
x.append(4,5,25)
x.append(5,6,6)
x.append(6,0,52)
x.append(7,4,11)
x.shape()

x_t = SparseMatrix.transpose(x)
x_t.print_matrix()

[[ 0.  0. 23.  0.  0.  0. 52.  0.]
 [ 0.  0.  0.  0. 14.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 31.  0.  0.  0.  0.]
 [ 0.  7.  0.  0.  0.  0.  0. 11.]
 [ 0.  0.  0.  0. 25.  0.  0.  0.]
 [12.  0.  0.  0.  0.  6.  0.  0.]]


In [ ]:
x = SparseMatrix(2,2)
y = SparseMatrix(2,2)
x.append(0,0,1)
x.append(1,1,4)
y.append(0,1,1)
y.append(1,0,2)

z = SparseMatrix.add(x,y)
z.s

[[2, 2, 4], [0, 1, 1], [1, 0, 2], [1, 1, 4], [0, 0, 1]]

In [23]:
class Node:
    def __init__(self, item=None, link=None):
        self.item = item
        self.link = link

class CircleLinkedList:
    def __init__(self):
        self.root = None
        self.nNode = 0

    def append(self,item):
        curNode = self.root
        newNode = Node(item)
        if self.root is None:
            self.root = newNode
        else:
            while curNode.link != self.root:
                curNode = curNode.link
            curNode.link = newNode
        newNode.link = self.root
        self.tail = newNode
        self.nNode += 1

    def insert(self, k, item):
        curNode = self.root
        newNode = Node(item)
        if k == 0:
            newNode.link = self.root
            self.root = newNode
            self.tail.link = self.root
        elif k > 0 and k <= self.nNode:
            for i in range(k-1):
                curNode = curNode.link
            _tmp = curNode.link
            curNode.link = newNode
            newNode.link = _tmp
            self.nNode += 1
        else:
            print("Index Error")

    def delete(self, item):
        k = self.find(item)
        curNode = self.root
        if k == 0:
            self.root = self.root.link
            self.tail.link = self.root
        else:
            for i in range(k-1):
                curNode = curNode.link
            curNode.link  =  curNode.link.link
        if k == self.nNode - 1:
            self.tail = curNode

    def find(self, item):
        curNode = self.root
        k = 0
        while curNode.link != self.root:
            if item == curNode.item:
                return k
            else:
                curNode = curNode.link
                k += 1
        if item == curNode.item:
            return k
        else:
            return None

    def setCurrent(self, k):
        self.curNode = self.root
        for i in range(k):
            self.curNode = self.curNode.link

    def moveNext(self):
        self.curNode = self.curNode.link

    def print(self):
        curNode = self.root
        while curNode.link != self.root:
            print(curNode.item, end=' -> ')
            curNode = curNode.link
        print(curNode.item)

In [18]:
fruits = CircleLinkedList()
fruits.append("사과")
fruits.append("배")
fruits.append("딸기")
fruits.append("포도")
fruits.insert(0,"앵두")
fruits.print()

앵두 -> 사과 -> 배 -> 딸기 -> 포도


In [20]:
fruits.setCurrent(0)
for i in range(20):
    fruits.moveNext()
    print(fruits.curNode.item)

사과
배
딸기
포도
앵두
사과
배
딸기
포도
앵두
사과
배
딸기
포도
앵두
사과
배
딸기
포도
앵두


In [33]:
fruits = CircleLinkedList()
fruits.append("사과")
fruits.append("배")
fruits.append("딸기")
fruits.append("포도")
fruits.insert(4,"감")
fruits.print()

사과 -> 배 -> 딸기 -> 포도 -> 감


In [34]:
fruits.setCurrent(0)
for i in range(20):
    fruits.moveNext()
    print(fruits.curNode.item)

배
딸기
포도
감
사과
배
딸기
포도
감
사과
배
딸기
포도
감
사과
배
딸기
포도
감
사과


In [35]:
!pip install llist

In [39]:
from llist import sllist, dllist

lst1 = sllist(['1','2','3','4','5'])
lst1


sllist(['1', '2', '3', '4', '5'])

In [40]:
lst1.first.value

'1'

In [41]:
lst1.last.value

'5'

In [43]:
lst1.size

5

In [44]:
lst1.append('6')

<sllistnode('6')>

In [45]:
lst1.last.value

'6'

In [46]:
curNode = lst1.nodeat(1)
curNode.value

'2'

In [47]:
lst1.insertafter('7', curNode)


<sllistnode('7')>

In [48]:
lst1

sllist(['1', '2', '7', '3', '4', '5', '6'])

TypeError: Argument is not an sllistnode

In [51]:
lst2 = dllist(['1','2','3','4','5'])
lst2

dllist(['1', '2', '3', '4', '5'])

In [52]:
curNode = lst2.nodeat(0)
print(curNode.value)

1


In [53]:
curNode = lst2.nodeat(1)
print(curNode.value)

2
