In [1]:
import pandas as pd

from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [2]:
data = pd.read_csv('/gdrive/My Drive/ML/data/wisc_bc_data.csv', sep=",")

In [3]:
data.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,points_worst,symmetry_worst,dimension_worst
0,87139402,B,12.32,12.39,78.85,464.1,0.10280,0.06981,0.03987,0.03700,...,13.50,15.64,86.97,549.1,0.1385,0.1266,0.12420,0.09391,0.2827,0.06771
1,8910251,B,10.60,18.95,69.28,346.4,0.09688,0.11470,0.06387,0.02642,...,11.88,22.94,78.28,424.8,0.1213,0.2515,0.19160,0.07926,0.2940,0.07587
2,905520,B,11.04,16.83,70.92,373.2,0.10770,0.07804,0.03046,0.02480,...,12.41,26.44,79.93,471.4,0.1369,0.1482,0.10670,0.07431,0.2998,0.07881
3,868871,B,11.28,13.39,73.00,384.8,0.11640,0.11360,0.04635,0.04796,...,11.92,15.77,76.53,434.0,0.1367,0.1822,0.08669,0.08611,0.2102,0.06784
4,9012568,B,15.19,13.21,97.65,711.8,0.07963,0.06934,0.03393,0.02657,...,16.20,15.73,104.50,819.1,0.1126,0.1737,0.13620,0.08178,0.2487,0.06766


In [4]:
len(data)

569

In [5]:
data.shape

(569, 32)

In [6]:
res = data['diagnosis'].value_counts() # unique value count
print(res)

diagnosis
B    357
M    212
Name: count, dtype: int64


In [7]:
from sklearn import neighbors, datasets
import numpy as np

X = data.iloc[:,2:].to_numpy()

In [9]:
data['target'] = data['diagnosis'].map({'B': 0, 'M': 1})
y = np.array(data['target'])
X.shape, y.shape

((569, 30), (569,))

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((455, 30), (455,), (114, 30), (114,))

In [25]:
y_train.shape, y_train.sum()

((455,), 165)

In [12]:
!pip install imblearn

In [26]:
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE

In [27]:
oversample = RandomOverSampler(sampling_strategy='minority')
X_train_over, y_train_over = oversample.fit_resample(X_train,y_train)

In [28]:
X_train_over.shape, y_train_over.shape, y_train_over.sum()

((580, 30), (580,), 290)

In [29]:
y_train_over.sum() # 절반이 나와야 한다.

290

In [30]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion='entropy')
model.fit(X_train_over, y_train_over)
predicted = model.predict(X_test)

In [31]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, predicted))

[[63  4]
 [ 7 40]]


In [32]:
undersample = RandomUnderSampler(sampling_strategy='majority')
X_train_under, y_train_under = undersample.fit_resample(X_train,y_train)

In [33]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion='entropy')
model.fit(X_train_under, y_train_under)
predicted = model.predict(X_test)
print(metrics.confusion_matrix(y_test, predicted))

[[58  9]
 [ 3 44]]


In [34]:
sm = SMOTE()
X_train_resampled, y_train_resampled = sm.fit_resample(X_train,y_train)

In [35]:
X_train_resampled.shape, y_train_resampled.shape

((580, 30), (580,))

In [36]:
model = DecisionTreeClassifier(criterion='entropy')
model.fit(X_train_resampled, y_train_resampled)
predicted = model.predict(X_test)
print(metrics.confusion_matrix(y_test, predicted))

[[61  6]
 [ 6 41]]
