In [4]:
def f(x):
    if x > 0:
        return 1
    else:
        return 0

import numpy as np
x = np.array([[1,0,0], [1,0,1], [1,1,0], [1,1,1]])
t = np.array([0,0,0,1]) # AND
#t = np.array([0,1,1,1]) # OR
eta = 0.1
w = np.array([0.,0.,0.])

for iter in range(10):
    for i in range(len(x)): # 4가지 경우에 대해 루프
        fnet = f(np.dot(x[i], w))
        e = t[i] - fnet
        w[0] = w[0] + eta * e * x[i][0]
        w[1] = w[1] + eta * e * x[i][1]
        w[2] = w[2] + eta * e * x[i][2]
    print(w)


[0.1 0.1 0.1]
[0.  0.2 0.1]
[-0.1  0.2  0.1]
[-0.1  0.2  0.2]
[-0.2  0.2  0.1]
[-0.2  0.2  0.1]
[-0.2  0.2  0.1]
[-0.2  0.2  0.1]
[-0.2  0.2  0.1]
[-0.2  0.2  0.1]


In [5]:
for i in range(len(x)):
    fnet = f(np.dot(x[i], w))
    print(fnet)

0
0
0
1
