In [1]:
# xor1.ipynb
import numpy as np
def Sigmoid(x):
    return 1/(1+np.exp(-x))

lamda = 1
x=np.array([[0,0],[0,1],[1,0],[1,1]])
t=np.array([[0],[1],[1],[0]])

w1=2*np.random.rand(2,3)-1 # np.random.rand : 2*(0~1) 난수 -1 : -1 ~ 1
b1=2*np.random.rand(1,3)-1
w2=2*np.random.rand(3,1)-1

w1, b1, w2

(array([[ 0.56844277,  0.81622474,  0.46502801],
        [-0.92048892,  0.27489889,  0.77688694]]),
 array([[-0.0833947 ,  0.03333093, -0.08331384]]),
 array([[-0.70827029],
        [-0.16430805],
        [-0.45651361]]))

In [2]:
h=Sigmoid(np.dot(x,w1)+b1)
y=Sigmoid(np.dot(h,w2))
y

array([[0.34487273],
       [0.35685415],
       [0.30475214],
       [0.3208882 ]])

In [3]:
for i in range(1000):
    h=Sigmoid(np.dot(x,w1)+b1)
    y=Sigmoid(np.dot(h,w2)) # dot(): matrix multiplication.
    deltaY= np.multiply(y-t,np.multiply(y,(1-y))) # multiply(): Multiply arguments element-wise.
    temp = np.multiply(w2.transpose(),np.multiply(h,(1-h)))
    deltaH = deltaY * temp
    w2 = w2 - np.dot(h.transpose(),lamda*deltaY) # back propagation
    w1 = w1 - np.dot(x.transpose(),lamda*deltaH)
    b1 = b1- lamda*deltaH
print (y)


[[0.01852265]
 [0.98068862]
 [0.98064936]
 [0.01814339]]


In [4]:
print(w1)
print(w2)
print(b1)

[[ 0.35421065  0.34704318  0.40720332]
 [-0.44066593  0.02926081  0.73914967]]
[[-5.25611137]
 [ 4.87174801]
 [ 0.07609297]]
[[ 2.09221153 -1.83701936  0.03134294]
 [-1.99026344  1.99903982 -0.21785478]
 [-2.68431856  1.77549634 -0.23794221]
 [ 2.30329703 -2.17801605  0.01348985]]


In [ ]:
h=Sigmoid(np.dot(x,w1)+b1)
y=Sigmoid(np.dot(h,w2)) # dot(): matrix multiplication.
deltaY= np.multiply(y-t,np.multiply(y,(1-y))) # multiply(): Multiply arguments element-wise.
temp = np.multiply(w2.transpose(),np.multiply(h,(1-h)))
deltaH = deltaY * temp
w2 = w2 - np.dot(h.transpose(),lamda*deltaY) # back propagation
w1 = w1 - np.dot(x.transpose(),lamda*deltaH)
b1 = b1- lamda*deltaH

In [ ]:
h=Sigmoid(np.dot(x,w1)+b1)
y=Sigmoid(np.dot(h,w2)) # dot(): matrix multiplication
h.shape, y.shape

((4, 3), (4, 1))

In [ ]:
deltaY= np.multiply(y-t,np.multiply(y,(1-y)))
deltaY.shape

(4, 1)

In [ ]:
temp = np.multiply(w2.transpose(),np.multiply(h,(1-h)))
temp.shape

(4, 3)

In [ ]:
deltaH = deltaY * temp
deltaH.shape

(4, 3)