In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x = np.array([[0,0],[0,1],[1,0],[1,1]]).astype('float32')
y = np.array([[0],[1],[1],[0]]).astype('float32')
x, y

(array([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]], dtype=float32),
 array([[0.],
        [1.],
        [1.],
        [0.]], dtype=float32))

In [5]:
from tensorflow.keras import layers

#actFunc = 'sigmoid' # 학습이 안된다.
actFunc = 'relu' # 된다.
model = tf.keras.Sequential()
model.add(layers.Dense(10, activation=actFunc, input_dim=2))
model.add(layers.Dense(10, activation=actFunc))
model.add(layers.Dense(10, activation=actFunc))
model.add(layers.Dense(10, activation=actFunc))
model.add(layers.Dense(10, activation=actFunc))
model.add(layers.Dense(10, activation=actFunc))
model.add(layers.Dense(10, activation=actFunc))
model.add(layers.Dense(1, activation='sigmoid'))
sgd = tf.keras.optimizers.SGD(learning_rate=0.1)
model.compile(optimizer=sgd,loss='binary_crossentropy',metrics=['accuracy'])

In [6]:
model.fit(x, y, epochs=10000, batch_size=4, verbose=0)
model.evaluate(x, y)

1/1 [==============================] - 0s 166ms/step - loss: 9.7903e-06 - accuracy: 1.0000


[9.79027845460223e-06, 1.0]

In [7]:
predicted = model.predict(x)
predicted

1/1 [==============================] - 0s 118ms/step


array([[2.6087342e-05],
       [9.9999177e-01],
       [9.9999923e-01],
       [4.0890141e-06]], dtype=float32)